mutation CreateDemoUser @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  user_insert(data: {username: "demouser", passwordHash: "demopassword", role: "demo"})
}

query ListMenuItems @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  menuItems {
    id
    name
    description
    price
    type
    isAvailable
    imageUrl
  }
}

mutation CreateOrder($customerName: String!, $orderNumber: String!, $specialInstructions: String!, $status: String!, $totalPrice: Float!) @auth(level: USER) {
  order_insert(data: {customerName: $customerName, orderNumber: $orderNumber, orderTime_expr: "request.time", specialInstructions: $specialInstructions, status: $status, totalPrice: $totalPrice, takenById_expr: "auth.uid"})
}

query GetMyOrders @auth(level: USER) {
  orders(where: {takenById: {eq_expr: "auth.uid"}}) {
    id
    customerName
    orderNumber
    orderTime
    specialInstructions
    status
    totalPrice
  }
}