import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'pho-bo-tai',
    name: 'Phở Bò Tái',
    nameEn: 'Rare Beef Pho',
    description: 'Phở bò với thịt tái mềm, nước dùng đậm đà',
    price: 65000,
    category: 'Phở',
    imageUrl: '/images/pho-bo-tai.jpg',
    available: true,
  },
  {
    id: 'pho-bo-nam',
    name: 'Phở Bò Nạm',
    nameEn: 'Brisket Pho',
    description: 'Phở bò với nạm mềm, chín vừa',
    price: 60000,
    category: 'Phở',
    imageUrl: '/images/pho-bo-nam.jpg',
    available: true,
  },
  {
    id: 'pho-tai-nam-gan-sach',
    name: 'Phở Tái Nạm Gân Sách',
    nameEn: 'Special Beef Pho',
    description: 'Phở đặc biệt với tái, nạm, gân và sách',
    price: 75000,
    category: 'Phở',
    imageUrl: '/images/pho-dac-biet.jpg',
    available: true,
  },
  {
    id: 'pho-ga',
    name: 'Phở Gà',
    nameEn: 'Chicken Pho',
    description: 'Phở gà thơm ngon với thịt gà mềm',
    price: 55000,
    category: 'Phở',
    imageUrl: '/images/pho-ga.jpg',
    available: true,
  },
  {
    id: 'bun-bo-hue',
    name: 'Bún Bò Huế',
    nameEn: 'Hue Beef Noodle Soup',
    description: 'Bún bò Huế cay nồng đặc trưng',
    price: 60000,
    category: 'Bún',
    imageUrl: '/images/bun-bo-hue.jpg',
    available: true,
  },
  {
    id: 'goi-cuon',
    name: 'Gỏi Cuốn',
    nameEn: 'Fresh Spring Rolls',
    description: 'Gỏi cuốn tươi với tôm và thịt (2 cuốn)',
    price: 40000,
    category: 'Khai Vị',
    imageUrl: '/images/goi-cuon.jpg',
    available: true,
  },
  {
    id: 'cha-gio',
    name: 'Chả Giò',
    nameEn: 'Fried Spring Rolls',
    description: 'Chả giò giòn tan (4 cuốn)',
    price: 45000,
    category: 'Khai Vị',
    imageUrl: '/images/cha-gio.jpg',
    available: true,
  },
  {
    id: 'nuoc-ngot',
    name: 'Nước Ngọt',
    nameEn: 'Soft Drink',
    description: 'Coca, Pepsi, 7Up, Fanta',
    price: 15000,
    category: 'Đồ Uống',
    imageUrl: '/images/nuoc-ngot.jpg',
    available: true,
  },
  {
    id: 'tra-da',
    name: 'Trà Đá',
    nameEn: 'Iced Tea',
    description: 'Trà đá tươi mát',
    price: 10000,
    category: 'Đồ Uống',
    imageUrl: '/images/tra-da.jpg',
    available: true,
  },
  {
    id: 'nuoc-cam',
    name: 'Nước Cam',
    nameEn: 'Orange Juice',
    description: 'Nước cam tươi ép',
    price: 25000,
    category: 'Đồ Uống',
    imageUrl: '/images/nuoc-cam.jpg',
    available: true,
  },
];

export const categories = [
  'Tất Cả',
  'Phở',
  'Bún',
  'Khai Vị',
  'Đồ Uống',
];
